version: 2

sources:
  - name: nytaxi
    schema: nytaxi
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
      - name: fhv_tripdata_2019

models:
  - name: stg_yellow_tripdata
    columns:
      - name: payment_type
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false

  - name: stg_green_tripdata
    columns:
      - name: payment_type
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false
